name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      - name: Setup the dotenv file
        run: mv ./.env.example ./.env

      - name: Build all artifacts
        run: cargo build --verbose --workspace --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os == 'windows-latest' && './target/release/thanatos.exe' || './target/release/thanatos' }}
